# Redis local (rodando Spring em IDE + Redis em máquina)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000
spring.data.redis.database=0

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.redis=DEBUG
