# Redis em Docker (Spring e Redis em Docker Compose)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.timeout=5000
spring.data.redis.database=0

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.redis=DEBUG